#
# THIS FILE IS GENERATED. SEE https://github.com/Chia-Network/chia-blockchain/tree/main/tests#readme
#
name: Windows core-daemon Test

on:
  push:
    branches:
      - main
    tags:
        - '**'
  pull_request:
    branches:
      - '**'

concurrency:
  # SHA is added to the end if on `main` to let all main workflows run
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}-${{ github.ref == 'refs/heads/main' && github.sha || '' }}
  cancel-in-progress: true

jobs:
  build:
    name: Windows core-daemon Test
    runs-on: ${{ matrix.os }}
    timeout-minutes: 30
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]
        os: [windows-latest]
    env:
      CHIA_ROOT: ${{ github.workspace }}/.chia/mainnet
      JOB_FILE_NAME: tests_${{ matrix.os }}_python-${{ matrix.python-version }}_core-daemon

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Python environment
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Cache npm
      uses: actions/cache@v2.1.6
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Get pip cache dir
      id: pip-cache
      run: |
        echo "::set-output name=dir::$(pip cache dir)"

    - name: Cache pip
      uses: actions/cache@v2.1.6
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Checkout test blocks and plots
      uses: actions/checkout@v3
      with:
        repository: 'Chia-Network/test-cache'
        path: '.chia'
        ref: '0.28.0'
        fetch-depth: 1

    - name: Run install script
      env:
        INSTALL_PYTHON_VERSION: ${{ matrix.python-version }}
      run: |
        ./Install.ps1

    - name: Install Ubuntu dependencies
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        sudo apt-get install software-properties-common
        sudo add-apt-repository ppa:deadsnakes/ppa
        sudo apt-get update
        sudo apt-get install python${{ matrix.python-version }}-venv python${{ matrix.python-version }}-distutils git -y

    - name: Install timelord
      run: |
        . ./activate
        sh install-timelord.sh
        ./vdf_bench square_asm 400000

    - name: Test core-daemon code with pytest
      run: |
        sed -i 's/found = _win32sysloader.GetModuleFilename(filename)/print(f\"GetModuleFilename(\{filename!r\})\"; found = _win32sysloader.GetModuleFilename(filename)/' venv/Lib/site-packages/win32/lib/pywintypes.py
        venv/Scripts/python -c "print(' ==== about to import pkg_resources'); import pkg_resources; print(' ==== just imported pkg_resources')"
        venv/Scripts/python -c "print(' ==== about to import tests.conftest'); import tests.conftest; print(' ==== just imported tests.conftest')"
        ./venv/Scripts/activate.ps1
        venv/Scripts/coverage run --rcfile=.coveragerc --module pytest tests/core/daemon/test_*.py -s -v --durations 0 -n 0 -m "not benchmark" -p no:monitor

    - name: Process coverage data
      run: |
        venv/Scripts/coverage combine --rcfile=.coveragerc .coverage.*
        venv/Scripts/coverage xml --rcfile=.coveragerc -o coverage.xml
        mkdir coverage_reports
        cp .coverage "coverage_reports/.coverage.${{ env.JOB_FILE_NAME }}"
        cp coverage.xml "coverage_reports/coverage.${{ env.JOB_FILE_NAME }}.xml"
        venv/Scripts/coverage report --rcfile=.coveragerc --show-missing

    - name: Publish coverage
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage_reports/*
        if-no-files-found: error

# Omitted resource usage check

#
# THIS FILE IS GENERATED. SEE https://github.com/Chia-Network/chia-blockchain/tree/main/tests#readme
#
